name: aanza_user
version: 1.0.0+1
publish_to: none
description: Aanza Food User App
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.0
  flutter_local_notifications: ^9.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

